
package com.lion.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LionStubWS", targetNamespace = "http://stub.lion.com", wsdlLocation = "http://arga-pc:8080/LionAirStub/services/LionStubWS?wsdl")
public class LionStubWS
    extends Service
{

    private final static URL LIONSTUBWS_WSDL_LOCATION;
    private final static WebServiceException LIONSTUBWS_EXCEPTION;
    private final static QName LIONSTUBWS_QNAME = new QName("http://stub.lion.com", "LionStubWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://arga-pc:8080/LionAirStub/services/LionStubWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIONSTUBWS_WSDL_LOCATION = url;
        LIONSTUBWS_EXCEPTION = e;
    }

    public LionStubWS() {
        super(__getWsdlLocation(), LIONSTUBWS_QNAME);
    }

    public LionStubWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), LIONSTUBWS_QNAME, features);
    }

    public LionStubWS(URL wsdlLocation) {
        super(wsdlLocation, LIONSTUBWS_QNAME);
    }

    public LionStubWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LIONSTUBWS_QNAME, features);
    }

    public LionStubWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LionStubWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LionStubWSPortType
     */
    @WebEndpoint(name = "LionStubWSHttpSoap11Endpoint")
    public LionStubWSPortType getLionStubWSHttpSoap11Endpoint() {
        return super.getPort(new QName("http://stub.lion.com", "LionStubWSHttpSoap11Endpoint"), LionStubWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LionStubWSPortType
     */
    @WebEndpoint(name = "LionStubWSHttpSoap11Endpoint")
    public LionStubWSPortType getLionStubWSHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://stub.lion.com", "LionStubWSHttpSoap11Endpoint"), LionStubWSPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIONSTUBWS_EXCEPTION!= null) {
            throw LIONSTUBWS_EXCEPTION;
        }
        return LIONSTUBWS_WSDL_LOCATION;
    }

}
